#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$script_dir"

# env
direnv allow .
if [[ "${UPDATE_FLAKE:-}" == "1" ]]; then
  nix flake update
fi

# e2e tests
direnv exec . npx playwright test --config Tests/E2E/playwright.config.ts
