#!/usr/bin/env bash
set -euo pipefail

# env
direnv allow .
if [[ "${UPDATE_FLAKE:-}" == "1" ]]; then
  nix flake update
fi

# purescript (always regenerate Proto/*.purs)
direnv exec . runghc proto/Purescript-Bridge.hs
direnv exec . bash -lc 'cd purescript && spago bundle-app --main Main --to ../static/ps-bundle.js --purs-args "--output output"'

# run
devenv up
