#!/usr/bin/env bash
set -euo pipefail

# env
direnv allow .
if [[ -z "${DEVENV_IN_DIRENV_SHELL:-}" ]]; then
  exec direnv exec . "$0" "$@"
fi
if [[ "${UPDATE_FLAKE:-}" == "1" ]]; then
  nix flake update
fi

# purescript
## Generate Types and Enums
make build/Generated/Types.hs
make build/Generated/Enums.hs
## generate proto/*.purs
runghc proto/Purescript-Bridge.hs
## generate static/ps-bundle.js
bash -lc 'cd purescript && spago bundle-app --main Main --to ../static/ps-bundle.js --purs-args "--output output"'

# smoke test
./smoke

# run
devenv up
