#!/usr/bin/env bash
set -euo pipefail

# env
direnv allow .
if [[ "${UPDATE_FLAKE:-}" == "1" ]]; then
  nix flake update
fi

## generate proto/*.purs
direnv exec . runghc proto/Purescript-Bridge.hs

# purescript tests
direnv exec . bash -lc 'cd purescript && spago test --main Test.Main'

# backend tests (mocked/pure)
direnv exec . bash -lc 'runghc $(make print-ghc-extensions) -i. -ibuild -iConfig Tests/Main.hs'
