#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$script_dir"

# env
direnv allow .
if [[ "${UPDATE_FLAKE:-}" == "1" ]]; then
  nix flake update
fi

## generate proto/*.purs
direnv exec . runghc proto/Purescript-Bridge.hs

# purescript tests
direnv exec . bash -lc 'cd purescript && spago test --main Test.Unit.Main'
direnv exec . bash -lc 'cd purescript && spago test --main Test.Integration.Main'

# backend tests
direnv exec . bash -lc 'runghc $(make print-ghc-extensions) -i. -ibuild -iConfig Tests/Main.hs'
